### [데이터 필터링]
* DataFrame/Series에서 원하는 데이터만 추출
    * 불린인덱싱
    * 메서드 .isin()
    * 메서드 .query()

In [21]:
# [1] 모듈 로딩 및 데이터 준비
import pandas as pd
DATA_FILE = '../DATA/학생관리부.xlsx'

In [22]:
# [2] 데이터 로딩 및 기본 정보 출력
dataDF = pd.read_excel(DATA_FILE, header=2)
dataDF

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [24]:
# [3] 특정 조건에 맞는 데이터만 추출(필터링)
# [3-1] 석차가 상위 10위까지만 데이터 추출
bool_sr = dataDF[dataDF.columns[-1]]<=10
bool_sr

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [26]:
# 상위 10위안에 있는 데이터만 추출
dataDF[bool_sr]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
3  박길동   3  1    9

In [29]:
# 상위 10위 밖에 있는 데이터만 추출
# ~ : not 연산자 = 현재 결과를 반대로
dataDF[~bool_sr]

    이름  학년  반   석차
2  이길동   1  7   12
4  최길동   2  1   43

In [32]:
# [3-2] 1학년 중에 상위 10위안에 들어가는 학생 데이터
# => 학년 컬럼 == 1, 석차 컬럼 <= 10 : 두개 조건 모두 만족
dataDF[dataDF.columns[1]], dataDF[dataDF.columns[-1]]

(0    1
 1    1
 2    1
 3    3
 4    2
 Name: 학년, dtype: int64,
 0     8
 1     1
 2    12
 3     9
 4    43
 Name:  석차, dtype: int64)

In [33]:
## -> 학년 컬럼 == 1
dataDF[dataDF.columns[1]] == 1

0     True
1     True
2     True
3    False
4    False
Name: 학년, dtype: bool

In [35]:
## -> 석차 컬럼 <= 10
dataDF[dataDF.columns[-1]] <= 10

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [39]:
## -> 학년 == 1 and 석차 <= 10
mask_sr = (dataDF[dataDF.columns[1]] == 1) & (dataDF[dataDF.columns[-1]] <= 10)
mask_sr

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [40]:
dataDF[mask_sr]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1