In [52]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Win11Pro\Desktop\KDT-14\[3]데이터시각화\DATA\bike_rentals.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  object
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB

In [53]:
# int 타입만 선택
df.select_dtypes(include='int')

,season,holiday,workingday,weather,humidity,casual,registered,count
0,1,0,0,1,81,3,13,16
1,1,0,0,1,80,8,32,40
2,1,0,0,1,80,5,27,32
3,1,0,0,1,75,3,10,13
4,1,0,0,1,75,0,1,1
...,...,...,...,...,...,...,...,...
10881,4,0,1,1,50,7,329,336
10882,4,0,1,1,57,10,231,241
10883,4,0,1,1,61,4,164,168
10884,4,0,1,1,61,12,117,129
10885,4,0,1,1,66,4,84,88

In [54]:
# int 타입 제외 선택
df.select_dtypes(exclude='int')

                  datetime   temp   atemp  windspeed
0      2011-01-01 00:00:00   9.84  14.395     0.0000
1      2011-01-01 01:00:00   9.02  13.635     0.0000
2      2011-01-01 02:00:00   9.02  13.635     0.0000
3      2011-01-01 03:00:00   9.84  14.395     0.0000
4      2011-01-01 04:00:00   9.84  14.395     0.0000
...                    ...    ...     ...        ...
10881  2012-12-19 19:00:00  15.58  19.695    26.0027
10882  2012-12-19 20:00:00  14.76  17.425    15.0013
10883  2012-12-19 21:00:00  13.94  15.910    15.0013
10884  2012-12-19 22:00:00  13.94  17.425     6.0032
10885  2012-12-19 23:00:00  13.12  16.665     8.9981

[10886 rows x 4 columns]

In [55]:
# 새로운 인덱스 datetime(00:00:00) 추가
df = df.set_index('datetime')
df

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
datetime,,,,,,,,,,,
2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [56]:
# filter()으로 '00:00:00' 행만 출력
df.filter(like='00:00:00', axis=0)

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
datetime,,,,,,,,,,,
2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
2011-01-02 00:00:00,1,0,0,2,18.86,22.725,88,19.9995,4,13,17
2011-01-03 00:00:00,1,0,1,1,9.02,9.850,44,23.9994,0,5,5
2011-01-04 00:00:00,1,0,1,1,6.56,9.090,55,7.0015,0,5,5
2011-01-05 00:00:00,1,0,1,1,8.20,12.880,64,0.0000,0,6,6
...,...,...,...,...,...,...,...,...,...,...,...
2012-12-15 00:00:00,4,0,0,1,12.30,16.665,70,0.0000,4,90,94
2012-12-16 00:00:00,4,0,0,2,14.76,18.940,62,0.0000,8,102,110
2012-12-17 00:00:00,4,0,1,2,15.58,19.695,87,0.0000,2,26,28
2012-12-18 00:00:00,4,0,1,2,18.04,21.970,94,8.9981,0,18,18
2012-12-19 00:00:00,4,0,1,1,12.30,15.910,61,0.0000,6,35,41

In [57]:
# 'humidity', 'windspeed' 행만 출력
df.filter(items=['humidity', 'windspeed'])

                     humidity  windspeed
datetime
2011-01-01 00:00:00        81     0.0000
2011-01-01 01:00:00        80     0.0000
2011-01-01 02:00:00        80     0.0000
2011-01-01 03:00:00        75     0.0000
2011-01-01 04:00:00        75     0.0000
...                       ...        ...
2012-12-19 19:00:00        50    26.0027
2012-12-19 20:00:00        57    15.0013
2012-12-19 21:00:00        61    15.0013
2012-12-19 22:00:00        61     6.0032
2012-12-19 23:00:00        66     8.9981

[10886 rows x 2 columns]

In [58]:
# 정규 표현식 사용 = regex=''
# 'in.s' => in 과 s 사이의 임의의 한문자를 지니는 열 => w'inds'peed
# .은 숫자와 알파벳 등을 포함한 임의의 문자 1개
df.filter(regex='in.s')

                     windspeed
datetime
2011-01-01 00:00:00     0.0000
2011-01-01 01:00:00     0.0000
2011-01-01 02:00:00     0.0000
2011-01-01 03:00:00     0.0000
2011-01-01 04:00:00     0.0000
...                        ...
2012-12-19 19:00:00    26.0027
2012-12-19 20:00:00    15.0013
2012-12-19 21:00:00    15.0013
2012-12-19 22:00:00     6.0032
2012-12-19 23:00:00     8.9981

[10886 rows x 1 columns]

In [59]:
# 행 이름 변경
df = df.rename(
    {'registered':'registered_user',
     'casual':'unregistered_user'},
     axis=1
)
# df.rename(
#     columns = {'registered':'registered_user',
#      'casual':'unregistered_user'}
# )
df

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,unregistered_user,registered_user,count
datetime,,,,,,,,,,,
2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [60]:
df = pd.read_csv(r'C:\Users\Win11Pro\Desktop\KDT-14\[3]데이터시각화\DATA\Bookings.csv')
df

,Hotel_Name,Review,Total_Review,Rating,Location
0,Oakwood Residence Midtown East,Superb,28,9.1,Murray Hill
1,Murray Hill East Suites,Good,52,7.6,Murray Hill
2,The Herald 8 by LuxUrban,Good,"2,870",7.8,Manhattan
3,"The Cloud One New York-Downtown, by the Motel ...",Very good,975,8.3,Wall Street - Financial District
4,Pod Times Square,Very good,"13,951",8.1,Hell's Kitchen
...,...,...,...,...,...
520,Fantastic 3BR At Financial District,NaN,NaN,NaN,Wall Street - Financial District
521,3 Bedroom Apartment In Midtown East,NaN,NaN,NaN,Manhattan
522,2BD 1BA Apartment At Financial District,NaN,NaN,NaN,Wall Street - Financial District
523,2BD 1BA Apartment At Wall Street,NaN,NaN,NaN,Wall Street - Financial District
524,Two BD Apartment At Midtown East,NaN,NaN,NaN,Manhattan

In [61]:
# 수치형 데이터 요약 정보 출력 해주는 메서드
df.describe()
# 범주형 데이터 정보 출력
df.describe(include='object')

                            Hotel_Name      Review Total_Review    Location
count                              525         325          325         525
unique                             498           8          255          25
top     Oakwood Residence Midtown East  Very good      1 review  Manhattan
freq                                 2         117            5         112

In [62]:
df['Review'].value_counts()

Review
Very good         117
Good              116
Review score       31
Fabulous           30
Superb             16
Superb 9.0          8
Exceptional         5
Exceptional 10      2
Name: count, dtype: int64

In [63]:
# 비슷해 보이는 값 합치기
df['Review'].str.strip()
df.loc[df['Review'] == 'Superb 9.0', 'Review'] = 'Superb'
df.loc[df['Review'] == 'Exceptional 10', 'Review'] = 'Exceptional'
df['Review'].value_counts()

Review
Very good        117
Good             116
Review score      31
Fabulous          30
Superb            16
Superb             8
Exceptional        5
Exceptional        2
Name: count, dtype: int64